# Generated by Django 2.2.22 on 2021-05-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20150529_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='email',
            field=models.EmailField(default='imas.datamanager@utas.edu.au', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='guide_pdf',
            field=models.FileField(null=True, upload_to='guide'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_image',
            field=models.ImageField(help_text="This is the image uses on the homepage.  It needs to be high res so it looks good and it needs to be fairly dark so that the copy has good contrast and can be easily read. We will optimise the size so it's not too heavy.", null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_image_credit_name',
            field=models.CharField(default='XXX', max_length=128),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='portal_record_url',
            field=models.CharField(default='{{site.sitecontent.portal_url}}/portal/home?uuid={{document.uuid}}', help_text='Used to generate URLs to the published record on the portal. (Accepts django template formatting with access to `site` and `document`.)', max_length=512),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='portal_title',
            field=models.CharField(default='IMAS Data Portal', help_text='Used to refer to the place where lodged data can be discovered', max_length=64),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='tag_line',
            field=models.CharField(default='Data Submission Tool', max_length=128),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='title',
            field=models.CharField(default='IMAS', max_length=32),
        ),
    ]
