# Generated by Django 2.1.7 on 2019-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20190808_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='portal_title',
            field=models.CharField(default='TERN Data Portal', help_text='Used to refer to the place where lodged data can be discovered', max_length=64),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='title',
            field=models.CharField(default='TERN', max_length=32),
        ),
    ]
