# Generated by Django 2.1.7 on 2019-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20190816_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='terms_pdf',
            field=models.FileField(null=True, upload_to='terms'),
        ),
    ]
