# Generated by Django 2.1.7 on 2019-09-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_sitecontent_terms_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='doiUri',
            field=models.CharField(default='https://doi.tern.uq.edu.au/test/index.php?r=api/create&user_id=tern.data@uq.edu.au', max_length=1024),
        ),
    ]
