# Generated by Django 2.1.7 on 2019-09-18 01:55

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_sitecontent_doiuri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='doiUri',
            field=models.CharField(default='https://doi.tern.uq.edu.au/test/index.php?r=api/create&user_id=tern.data@uq.edu.au', help_text='Base create URI for the DOI minting service', max_length=1024, verbose_name='DOI Service URI'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text="This is the image used on the homepage.  It needs to be high res so it looks good and it needs to be fairly dark so that the copy has good contrast and can be easily read. We will optimise the size so it's not too heavy.", null=True, upload_to='images'),
        ),
    ]
