# Generated by Django 2.1.7 on 2019-10-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20190918_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='email',
            field=models.EmailField(default='esupport@tern.org.au', max_length=254),
        ),
    ]
