# Generated by Django 2.1.7 on 2019-10-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20191004_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='doi_uri',
            field=models.CharField(default='https://doi.tern.uq.edu.au/test/index.php?r=api/create&user_id=tern.data@uq.edu.au&app_id=', help_text='Base create URI for the DOI minting service', max_length=1024, verbose_name='DOI Service URI'),
        ),
    ]
