# Generated by Django 2.1.7 on 2019-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20191008_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='releasenotes_url',
            field=models.URLField(blank=True, null=True, verbose_name='Release notes URL'),
        ),
    ]
