# Generated by Django 2.1.7 on 2019-08-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataTemplateMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for template mapper.  Used in menus.', max_length=128)),
                ('file', models.FileField(help_text='JSON file used to interpret XML files that specify records', upload_to='', verbose_name='metadata_template_mappers')),
                ('notes', models.TextField(help_text='Internal use notes about this template mapper')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
        ),
        migrations.AddField(
            model_name='metadatatemplate',
            name='mapper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.MetadataTemplateMapper'),
        ),
    ]
