# Generated by Django 2.1.7 on 2019-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190814_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
    ]
