# Generated by Django 2.1.7 on 2019-11-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191111_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='anzsrckeyword',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sciencekeyword',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
