# Generated by Django 2.1.7 on 2019-08-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_document_agreed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='agreed',
        ),
    ]
