# Generated by Django 2.1.7 on 2019-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_document_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftmetadata',
            name='agreedToTerms',
            field=models.BooleanField(default=False),
        ),
    ]
