# Generated by Django 2.1.7 on 2019-08-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_samplingfrequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['familyName', 'givenName']},
        ),
        migrations.AddField(
            model_name='person',
            name='orcid',
            field=models.CharField(default='', max_length=50, verbose_name='ORCID ID'),
        ),
    ]
