# Generated by Django 2.1.7 on 2020-02-28 01:16

from django.db import migrations


def add_extra_keywords(apps, schema_editor):
    # We can't import the DraftMetadata model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    DraftMetadata = apps.get_model('backend', 'DraftMetadata')
    for dm in DraftMetadata.objects.all():
        idinfo = dm.data['identificationInfo']
        for field in ('keywordsTaxonExtra', 'keywordsThemeExtra'):
            if field not in idinfo:
                idinfo[field] = {}
            if ('keywords' not in idinfo[field]) or (idinfo[field]['keywords'] is None):
                idinfo[field]['keywords'] = []
                dm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_initial_data'),
    ]

    operations = [
        migrations.RunPython(add_extra_keywords),
    ]
