# Generated by Django 2.1.7 on 2019-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_topiccategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiccategory',
            options={'ordering': ['identifier']},
        ),
        migrations.RemoveField(
            model_name='samplingfrequency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='samplingfrequency',
            name='uri',
            field=models.CharField(default='', max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='identifier',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
