# Generated by Django 2.1.7 on 2019-09-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190828_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isUserAdded',
            field=models.BooleanField(default=False, verbose_name='User Added'),
        ),
        migrations.AddField(
            model_name='person',
            name='prefLabel',
            field=models.CharField(default='', max_length=512),
        ),
    ]
