# Generated by Django 2.1.7 on 2019-09-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.AddField(
            model_name='person',
            name='electronicMailAddress',
            field=models.CharField(default='', max_length=256, verbose_name='email'),
        ),
    ]
