# Generated by Django 2.1.7 on 2019-09-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190917_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftmetadata',
            name='doiRequested',
            field=models.BooleanField(default=False),
        ),
    ]
