# Generated by Django 2.1.7 on 2019-09-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_draftmetadata_doirequested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('workflow_reject', 'Can reject record in workflow'), ('workflow_upload', 'Can upload record in workflow'), ('workflow_discard', 'Can discard record in workflow'), ('workflow_restart', 'Can restart record in workflow'), ('workflow_recover', 'Can recover discarded records in workflow'), ('workflow_mint', 'Can queue a DOI to be minted in workflow'))},
        ),
    ]
