# Generated by Django 2.1.7 on 2019-09-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20190918_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doi',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
