# Generated by Django 2.1.7 on 2019-09-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_document_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doi',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
