# Generated by Django 2.1.7 on 2019-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20190918_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doi',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
