# Generated by Django 2.1.7 on 2019-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_anzsrckeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anzsrckeyword',
            name='UUID',
            field=models.CharField(default='', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
