# Generated by Django 2.1.7 on 2019-09-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20190919_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingfrequency',
            name='prefLabelSortText',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='anzsrckeyword',
            name='UUID',
            field=models.CharField(default='', editable=False, max_length=256, primary_key=True, serialize=False, verbose_name='URL'),
        ),
    ]
