# Generated by Django 2.1.7 on 2019-09-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20190920_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorizontalFrequency',
            fields=[
                ('uri', models.CharField(default='', max_length=512, primary_key=True, serialize=False)),
                ('prefLabel', models.CharField(max_length=256)),
                ('prefLabelSortText', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
