# Generated by Django 2.1.7 on 2019-09-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_horizontalfrequency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HorizontalFrequency',
            new_name='HorizontalResolution',
        ),
    ]
