# Generated by Django 2.1.7 on 2019-09-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20190923_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='isUserAdded',
            field=models.BooleanField(default=False, verbose_name='User Added'),
        ),
    ]
