# Generated by Django 2.1.7 on 2019-09-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_institution_isuseradded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecode',
            name='Description',
            field=models.CharField(max_length=256),
        ),
    ]
