# Generated by Django 2.1.7 on 2019-09-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20190924_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='honorificPrefix',
            field=models.CharField(blank=True, max_length=256, verbose_name='honorific'),
        ),
    ]
