# Generated by Django 2.1.7 on 2019-10-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20190927_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ORCID ID'),
        ),
    ]
