# Generated by Django 2.1.7 on 2019-10-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20191004_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('workflow_reject', 'Can reject record in workflow'), ('workflow_upload', 'Can upload record in workflow'), ('workflow_discard', 'Can discard record in workflow'), ('workflow_restart', 'Can restart record in workflow'), ('workflow_recover', 'Can recover discarded records in workflow'))},
        ),
    ]
