# Generated by Django 2.1.7 on 2019-10-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20191004_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='electronicMailAddress',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='familyName',
            field=models.CharField(blank=True, max_length=256, verbose_name='family name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='givenName',
            field=models.CharField(blank=True, max_length=256, verbose_name='given name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='orgUri',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='person',
            name='prefLabel',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
