# Generated by Django 2.1.7 on 2019-12-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0005_auto_20191129_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='administrativeArea',
            field=models.CharField(max_length=100, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='postalCode',
            field=models.CharField(max_length=100, verbose_name='postcode'),
        ),
    ]
