# Generated by Django 3.2.7 on 2021-10-18 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('backend', '0012_auto_20211018_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterfaceTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for UI template.  Used in menus.', max_length=128)),
                ('file', models.FileField(help_text='EDN file used to define the UI needed for data capture', upload_to='', verbose_name='ui_template')),
                ('notes', models.TextField(blank=True, help_text='Internal use notes about this template mapper', null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
