# Generated by Django 2.1.7 on 2020-01-27 22:13
from datetime import datetime

import pytz
from django.db import migrations


def configure_backend_data(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    MetadataTemplateMapper = apps.get_model('backend', 'MetadataTemplateMapper')
    MetadataTemplate = apps.get_model('backend', 'MetadataTemplate')
    UserInterfaceTemplate = apps.get_model('backend', 'UserInterfaceTemplate')
    now = datetime.utcnow().replace(tzinfo=pytz.UTC)
    # Create default UserInterfaceTemplate
    uit = UserInterfaceTemplate.objects.create()
    uit.name = 'TERN UI'
    uit.file = 'tern_ui.edn'
    uit.notes = 'Default UI (WIP)'
    uit.archived = 'f'
    uit.site_id = '1'
    uit.created = now
    uit.modified = now
    uit.save()
    # Create default MetadataTemplateMapper
    mtm, _ = MetadataTemplateMapper.objects.get_or_create(pk=1)
    mtm.name = 'Tern Mapper'
    mtm.file = 'tern_jsonschema_mapper.json'
    mtm.notes = 'Default template mapper (WIP)'
    mtm.archived = 'f'
    mtm.site_id = '1'
    mtm.created = now
    mtm.modified = now
    mtm.save()
    # Create default MetadataTemplate
    mt = MetadataTemplate.objects.create()
    mt.name = "TERN Template with uploaded UI"
    mt.file = "TERN_ISO_Profile_v0_01.xml"
    mt.notes = "Default template"
    mt.archived = "f"
    mt.site_id = "1"
    mt.mapper_id = mtm.pk
    mt.ui_template_id = uit.pk
    mt.created = now
    mt.modified = now
    mt.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0014_metadatatemplate_ui_template'),
        ('frontend', '0006_initial_data'),
    ]

    operations = [
        migrations.RunPython(configure_backend_data),
    ]
