# Generated by Django 3.2.7 on 2021-11-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftmetadata',
            name='hasUserDefined',
            field=models.BooleanField(default=False),
        ),
    ]
