# Generated by Django 3.2.7 on 2022-02-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20211118_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('label', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='document',
            name='publish_result',
            field=models.TextField(blank=True, null=True, verbose_name='Publish result'),
        ),
        migrations.AddField(
            model_name='document',
            name='publish_status',
            field=models.BooleanField(default=False, verbose_name='Publish status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='hasUserDefined',
            field=models.BooleanField(default=False, verbose_name='Has User-defined'),
        ),
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(to='backend.DocumentCategory'),
        ),
    ]
