# Generated by Django 3.2.7 on 2022-05-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20220401_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, to='backend.DocumentCategory'),
        ),
    ]
