# Generated by Django 3.2.7 on 2022-05-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_document_categories_data_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, to='backend.DocumentCategory'),
        ),
    ]
