# Generated by Django 3.2.7 on 2023-06-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_my_defaults(apps, schema_editor):
        DocumentAttachment = apps.get_model('backend', 'DocumentAttachment')
        for document_attachment in DocumentAttachment.objects.all().iterator():
            document_attachment.resourceId = document_attachment.id
            document_attachment.save()

    def reverse_func(apps, schema_editor):
        pass

    dependencies = [
        ('backend', '0022_alter_document_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentattachment',
            name='resourceId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='documentattachment',
            name='resourceId',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
