# Generated by Django 3.2.7 on 2023-06-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_documentattachment_resourceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentattachment',
            name='resourceId',
        ),
    ]
