image:
  name: ternau/bb-python:3.8.1-alpine

# cloning another repo in pipeline
# https://bitbucket.org/blog/cloning-another-bitbucket-repository-in-bitbucket-pipelines
# TODO: I like the node cache ... need to do something about tern-react pkg caching .... properly version it?

definitions:
  # define custom cache for frontend/node_modules
  caches:
    clojure: ~/.clojure
    frontend-node-modules: frontend/node_modules

  # generic re-usable steps
  steps:
    - step: &envstep
      # use a multiline step to set environment variables
      - script: &setenv |
          export IMAGE_NAME=ternau/data-submission-tool

    - step: &build-frontend-step
        caches:
          - maven
          - clojure
          - frontend-node-modules
        image:
          name: theasp/clojurescript-nodejs:shadow-cljs-alpine
          run-as-user: 1000
        script:
          - cd frontend
          # clean
          - rm -fR src/gen/* resources/public/js/*
          # release build
          - yarn
          - yarn run build
          - yarn shadow-cljs release tern
          # copy-static step
          - npx sass --load-path=. --style compressed src/js/index.scss resources/public/css/style.npm-packaged.css
          - mkdir -p resources/public/resources/icons resources/public/css/images
          - cp -fR node_modules/@blueprintjs/icons/resources/icons resources/public/resources/icons
          - cp -vr node_modules/leaflet-draw/dist/images/* resources/public/css/images

    - step: &build-test-step
        script: &build-test
          - *setenv
          - make build
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          - make push
          # - CI=true npm test
        services:
          - docker

pipelines:

  branches:
    # development-release:
    pipeline-bb-fix:
      - step: *build-frontend-step
      - step: *build-test-step

  # pull-requests:
  #   '**':
  #     - step: *build-test-step
