version: '3'

services:

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 15

  web:
    build: .
    image: ternau/data-submission-tool

    env_file:
      - .env
    command: init python3 manage.py runserver 0.0.0.0:8000
    # command: init gunicorn --bind 0.0.0.0:8000 --workers=5 --forwarded-allow-ips='*' webapp.wsgi
    user: "1000:1000"
    volumes:
      - ./docker-files/local_settings.py:/etc/data-submission-tool/settings.py
      - ./docker-files/docker_entrypoint.sh:/docker_entrypoint.sh
      - .:/data-submission-tool
      - ./frontend/resources:/data-submission-tool/frontend/resources
      # mount storage into container
      - ./volumes/data-submission-tool/static:/data/static
      - ./volumes/data-submission-tool/media:/data/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    user: "1000:1000"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/es-data:/usr/share/elasticsearch/data

  gn:
    # Account: admin/admin
    image: geonetwork
    ports:
      - 8080:8080
    environment:
      DATA_DIR: /var/lib/geonetwork_data
      ES_HOST: es
    volumes:
      - ./volumes/geonetwork:/var/lib/geonetwork_data

  web2:
    build: .
    image: ternau/data-submission-tool

    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-metcalf.tern.webapp.settings}
    env_file:
      - .env
    command: init python3 manage.py runserver 0.0.0.0:8000
    # command: init gunicorn --bind 0.0.0.0:8000 --workers=5 --forwarded-allow-ips='*' webapp.wsgi
    user: "1000:1000"
    volumes:
      - ./docker-files/local_settings.py:/etc/data-submission-tool/settings.py
      - ./docker-files/docker_entrypoint.sh:/docker_entrypoint.sh
      - .:/data-submission-tool
      - ./frontend/resources:/data-submission-tool/frontend/resources
      # mount storage into container
      - ./volumes/data-submission-tool/static:/data/static
      - ./volumes/data-submission-tool/media:/data/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


  cron:
    image: ternau/data-submission-tool
    env_file:
      - .env
    command: /usr/local/bin/supercronic --prometheus-listen-address :9000  /etc/supercronic/crontab
    user: "1000:1000"
    volumes:
      - ./docker-files/crontab:/etc/dst/crontab
      - ./docker-files/local_settings.py:/etc/data-submission-tool/settings.py
      # mount source into container
      - .:/data-submission-tool
    ports:
      - "9000:9000"
    depends_on:
      - db
