# Generated by Django 3.2.7 on 2021-09-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20150529_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='guide_pdf',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Help'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_image',
            field=models.CharField(blank=True, help_text='Url to homepage image. (Accepts django template formatting with access to `site` and `sitecontent`.)', max_length=200, null=True, verbose_name='Homepage Image'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_image_credit_name',
            field=models.CharField(default='XXX', max_length=128),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='portal_record_url',
            field=models.CharField(default='{{site.sitecontent.portal_url}}/edit/{{document.uuid}}', help_text='Used to generate URLs to the published record on the portal. (Accepts django template formatting with access to `site` and `document`.)', max_length=512),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='portal_title',
            field=models.CharField(help_text='Used to refer to the place where lodged data can be discovered', max_length=64),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='tag_line',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='title',
            field=models.CharField(default='Data Submission Tool', max_length=32),
        ),
    ]
