# Generated by Django 3.2.7 on 2021-10-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210912_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_image',
            field=models.ImageField(help_text="This is the image used on the homepage.  It needs to be high res so it looks good and it needs to be fairly dark so that the copy has good contrast and can be easily read. We will optimise the size so it's not too heavy.", null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
