# Generated by Django 3.2.7 on 2021-11-12 23:08

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('base_url', models.CharField(max_length=200)),
                ('search_param', models.CharField(default='query', max_length=32)),
                ('response_key', models.CharField(default='results', max_length=128)),
                ('schema', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
    ]
