# Generated by Django 3.2.7 on 2021-11-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
