# Generated by Django 3.2.7 on 2022-05-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='code_location_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='code_location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='homepage_abstract',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='homepage_acknowledgements',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
