# Generated by Django 3.2.7 on 2023-01-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='code_location_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='code_location_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='geonetwork_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='homepage_abstract',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='homepage_acknowledgements',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
