# Generated by Django 3.2.7 on 2022-05-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20220526_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='code_location_name',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='code_location_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_abstract',
            field=models.CharField(blank=True, default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_acknowledgements',
            field=models.CharField(blank=True, default='', max_length=512),
            preserve_default=False,
        ),
    ]
