# Generated by Django 3.2.7 on 2023-01-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20220526_0257'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.AddField(
            model_name='sitecontent',
            name='geonetwork_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='code_location_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='code_location_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_abstract',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_acknowledgements',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
    ]
