# Generated by Django 3.2.7 on 2022-12-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20220526_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='geonetwork_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
