# Generated by Django 3.2.7 on 2023-01-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20230109_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='code_location_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='code_location_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_abstract',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_acknowledgements',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
