# Generated by Django 3.2.7 on 2022-12-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_sitecontent_geonetwork_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='geonetwork_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
