# Generated by Django 3.2.7 on 2022-12-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_sitecontent_geonetwork_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_abstract',
            field=models.CharField(blank=True, default='', max_length=512),
            preserve_default=False,
        ),
    ]
