# Generated by Django 3.2.7 on 2023-01-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_sitecontent_geonetwork_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='geonetwork_url',
            field=models.URLField(blank=True),
        ),
    ]
