import React from 'react';
import ReactDOM from 'react-dom';
import * as BlueprintCore from "@blueprintjs/core";
import * as BlueprintSelect from "@blueprintjs/select";
import * as BlueprintTable from "@blueprintjs/table";
import * as BlueprintDatetime from "@blueprintjs/datetime";
import MaskedInput from 'react-text-mask';
import moment from 'moment';
import * as ReactWindow from "react-window";
import * as ReactVirtualized from "react-virtualized";
import AutoSizer from "react-virtualized-auto-sizer";
import * as ReactLeaflet from "react-leaflet";
import 'leaflet-draw';
import { EditControl } from 'react-leaflet-draw';
import FixedDataTable2 from 'fixed-data-table-2';
import Select, { components } from "react-select";
import AsyncSelect from 'react-select/async';
import Creatable from 'react-select/creatable';
import AsyncCreatable from 'react-select/async-creatable';

window.React = React;
window.ReactDOM = ReactDOM;
window.BlueprintCore = BlueprintCore;
window.BlueprintSelect = BlueprintSelect;
window.BlueprintTable = BlueprintTable;
window.BlueprintDatetime = BlueprintDatetime;
window.MaskedInput = MaskedInput;
window.moment = moment;
window.ReactWindow = ReactWindow;
window.ReactVirtualized = ReactVirtualized;
window.AutoSizer = AutoSizer;
window.ReactLeaflet = ReactLeaflet;
window.ReactLeaflet.EditControl = EditControl;
window.FixedDataTable2 = FixedDataTable2;
window.Select = Select;
window.SelectComponents = components;
window.AsyncSelect = AsyncSelect;
window.Creatable = Creatable;
window.AsyncCreatable = AsyncCreatable;
