# Generated by Django 3.2.7 on 2021-11-19 00:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0004_auto_20211019_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
