# Generated by Django 3.2.7 on 2022-03-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220310_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftmetadata',
            name='doiRequested',
            field=models.BooleanField(default=False),
        ),
    ]
