# Generated by Django 2.2.22 on 2021-05-13 03:44

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=django_fsm.FSMField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Uploaded', 'Uploaded'), ('Archived', 'Archived'), ('Discarded', 'Discarded')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='institution',
            name='administrativeArea',
            field=models.CharField(max_length=64, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='deliveryPoint',
            field=models.CharField(max_length=256, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='deliveryPoint2',
            field=models.CharField(max_length=256, verbose_name='street address 2'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='organisationName',
            field=models.CharField(max_length=256, verbose_name='organisation name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='postalCode',
            field=models.CharField(max_length=16, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='metadatatemplate',
            name='file',
            field=models.FileField(help_text='XML file used when creating and exporting records', upload_to='', verbose_name='metadata_templates'),
        ),
        migrations.AlterField(
            model_name='metadatatemplate',
            name='name',
            field=models.CharField(help_text='Unique name for template.  Used in menus.', max_length=128),
        ),
        migrations.AlterField(
            model_name='metadatatemplate',
            name='notes',
            field=models.TextField(help_text='Internal use notes about this template'),
        ),
    ]
