# Generated by Django 2.1.7 on 2019-11-11 04:30

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='doi_uri',
            field=models.CharField(
                default='https://doi.tern.uq.edu.au/test/index.php?r=api/create&user_id=tern.data@uq.edu.au&app_id=',
                help_text='Base create URI for the DOI minting service', max_length=1024,
                verbose_name='DOI Service URI'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='homepage_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/Hemispherical-Photography.jpg',
                                                             help_text="This is the image used on the homepage.  It needs to be high res so it looks good and it needs to be fairly dark so that the copy has good contrast and can be easily read. We will optimise the size so it's not too heavy.",
                                                             null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='portal_url',
            field=models.URLField(blank=True, default='http://tern.org.au', null=True),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='tag_line',
            field=models.CharField(default='SHaRED Data Submission Tool', max_length=128, null=True),
        ),
    ]
