# Generated by Django 2.1.7 on 2019-11-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20191111_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='guide_pdf',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Help'),
        ),
    ]
