# Generated by Django 3.2.7 on 2021-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20200824_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
