# Generated by Django 3.2.7 on 2022-05-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_sitecontent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='geonetwork_url',
            field=models.URLField(default='https://geonetwork.tern.org.au/geonetwork/srv/eng/catalog.search#/metadata'),
            preserve_default=False,
        ),
    ]
