(ns metcalf3.config
  (:require [re-frame.core :as rf]
            [metcalf3.fx :as fx]
            [metcalf3.handlers :as handlers]
            [metcalf3.ins :as ins]
            [metcalf3.subs :as subs]))

(rf/reg-event-db :handlers/load-api-options-resp ins/std-ins handlers/load-api-options-resp)
(rf/reg-event-db :handlers/load-es-options-resp ins/std-ins handlers/load-es-options-resp)
(rf/reg-event-db :handlers/close-modal ins/std-ins handlers/close-modal)
(rf/reg-event-db :handlers/close-and-cancel ins/std-ins handlers/close-and-cancel)
(rf/reg-event-db :handlers/close-and-confirm ins/std-ins handlers/close-and-confirm)
(rf/reg-event-db :handlers/open-modal ins/std-ins handlers/open-modal)
(rf/reg-event-db :handlers/del-value ins/std-ins handlers/del-value)
(rf/reg-event-db :handlers/new-field! ins/std-ins handlers/new-field!)
(rf/reg-event-db :handlers/add-field! ins/std-ins handlers/add-field!)
(rf/reg-event-db :handlers/add-value! ins/std-ins handlers/add-value!)
(rf/reg-event-db :handlers/save-current-document-success ins/std-ins handlers/save-current-document-success)
(rf/reg-event-db :handlers/add-attachment ins/std-ins handlers/add-attachment)
(rf/reg-event-db :handlers/back handlers/back)
(rf/reg-event-db :handlers/update-dp-term ins/std-ins handlers/update-dp-term)
(rf/reg-event-db :handlers/update-nasa-list-value ins/std-ins handlers/update-nasa-list-value)
(rf/reg-event-db :handlers/update-boxes ins/std-ins handlers/update-boxes)
(rf/reg-event-db :handlers/update-method-term ins/std-ins handlers/update-method-term)
(rf/reg-event-db :handlers/update-method-name ins/std-ins handlers/update-method-name)
(rf/reg-event-db :handlers/setter ins/std-ins handlers/setter)
(rf/reg-event-db :handlers/check-unsaved-keyword-input ins/std-ins handlers/check-unsaved-keyword-input)
(rf/reg-event-db :handlers/remove-party ins/std-ins handlers/remove-party)
(rf/reg-event-db :handlers/reset-form ins/std-ins handlers/reset-form)
(rf/reg-event-db :handlers/show-errors ins/std-ins handlers/show-errors)
(rf/reg-event-db :handlers/hide-errors ins/std-ins handlers/hide-errors)
(rf/reg-event-db :handlers/toggle-status-filter ins/std-ins handlers/toggle-status-filter)
(rf/reg-event-db :handlers/show-all-documents ins/std-ins handlers/show-all-documents)
(rf/reg-event-db :handlers/load-error-page ins/std-ins handlers/load-error-page)
(rf/reg-event-db :handlers/set-value ins/std-ins handlers/set-value)
(rf/reg-event-db :date-field/value-change ins/std-ins handlers/value-change)
(rf/reg-event-db :textarea-field/value-change ins/std-ins handlers/value-change)
(rf/reg-event-db :handlers/set-geographic-element ins/std-ins handlers/set-geographic-element)
(rf/reg-event-db :handlers/person-detail-changed ins/std-ins handlers/person-detail-changed)
(rf/reg-event-db :handlers/value-changed ins/std-ins handlers/value-changed)
(rf/reg-event-db :handlers/set-tab ins/std-ins handlers/set-tab)
(rf/reg-event-db :handlers/load-errors ins/std-ins handlers/load-errors)
(rf/reg-event-db :handlers/add-keyword-extra ins/std-ins handlers/add-keyword-extra)
(rf/reg-event-db :handlers/del-keyword-extra ins/std-ins handlers/del-keyword-extra)
(rf/reg-event-db :handlers/add-nodes ins/std-ins handlers/add-nodes)
(rf/reg-event-db :handlers/dashboard-create-click ins/std-ins handlers/dashboard-create-click)
(rf/reg-event-db :handlers/transite-doc-success ins/std-ins handlers/transite-doc-success)
(rf/reg-event-db :handlers/lodge-submit-success ins/std-ins handlers/lodge-submit-success)
(rf/reg-event-fx :handlers/init-db ins/std-ins handlers/init-db)
(rf/reg-event-fx :handlers/load-api-options ins/std-ins handlers/load-api-options)
(rf/reg-event-fx :handlers/load-es-options ins/std-ins handlers/load-es-options)
(rf/reg-event-fx :handlers/search-es-options ins/std-ins handlers/search-es-options)
(rf/reg-event-fx :handlers/save-current-document ins/std-ins handlers/save-current-document)
(rf/reg-event-fx :handlers/save-current-document-error ins/std-ins handlers/save-current-document-error)
(rf/reg-event-fx :handlers/archive-current-document ins/std-ins handlers/archive-current-document)
(rf/reg-event-fx :handlers/archive-current-document-success ins/std-ins handlers/archive-current-document-success)
(rf/reg-event-fx :handlers/update-address ins/std-ins handlers/update-address)
(rf/reg-event-fx :handlers/update-person ins/std-ins handlers/update-person)
(rf/reg-event-fx :handlers/org-changed ins/std-ins handlers/org-changed)
(rf/reg-event-fx :handlers/create-document-success ins/std-ins handlers/create-document-success)
(rf/reg-event-fx :handlers/create-document-error ins/std-ins handlers/create-document-error)
(rf/reg-event-fx :handlers/dashboard-create-save ins/std-ins handlers/dashboard-create-save)
(rf/reg-event-fx :handlers/clone-document ins/std-ins handlers/clone-document)
(rf/reg-event-fx :handlers/clone-document-success ins/std-ins handlers/clone-document-success)
(rf/reg-event-fx :handlers/clone-document-error ins/std-ins handlers/clone-document-error)
(rf/reg-event-fx :handlers/archive-doc-click ins/std-ins (handlers/transite-doc-click "archive"))
(rf/reg-event-fx :handlers/delete-archived-doc-click ins/std-ins (handlers/transite-doc-click "delete_archived"))
(rf/reg-event-fx :handlers/restore-doc-click ins/std-ins (handlers/transite-doc-click "restore"))
(rf/reg-event-fx :handlers/transite-doc-confirm ins/std-ins handlers/transite-doc-confirm)
(rf/reg-event-fx :handlers/transite-doc-error ins/std-ins handlers/transite-doc-error)
(rf/reg-event-fx :handlers/lodge-click ins/std-ins handlers/lodge-click)
(rf/reg-event-fx :handlers/lodge-save-success ins/std-ins handlers/lodge-save-success)
(rf/reg-event-fx :handlers/lodge-error ins/std-ins handlers/lodge-error)
(rf/reg-event-fx :help-menu/open handlers/help-menu-open)
(rf/reg-fx :xhrio/get-json fx/xhrio-get-json)
(rf/reg-fx :xhrio/post-json fx/xhrio-post-json)
(rf/reg-fx :fx/set-location-href fx/set-location-href)
(rf/reg-fx :fx/create-document fx/create-document)
(rf/reg-fx :fx/clone-document fx/clone-document)
(rf/reg-fx :fx/transition-current-document fx/transition-current-document)
(rf/reg-fx :fx/submit-current-document fx/submit-current-document)
(rf/reg-fx :fx/save-current-document fx/save-current-document)
(rf/reg-fx :fx/archive-current-document fx/archive-current-document)
(rf/reg-fx :window/open fx/window-open)
(rf/reg-sub :subs/get-derived-state subs/get-derived-state)
(rf/reg-sub :metcalf3/form-dirty? [:subs/get-derived-state] subs/form-dirty?)
(rf/reg-sub :subs/is-page-name-nil? subs/is-page-name-nil?)
(rf/reg-sub :subs/get-derived-path [:subs/get-derived-state] subs/get-derived-path)
(rf/reg-sub :subs/get-page-props subs/get-page-props)
(rf/reg-sub :subs/get-page-name subs/get-page-name)
(rf/reg-sub :subs/get-modal-props subs/get-modal-props)
(rf/reg-sub :subs/get-dashboard-props subs/get-dashboard-props)
(rf/reg-sub :subs/get-edit-tab-props :<- [:subs/get-page-props] [:subs/get-derived-state] subs/get-edit-tab-props)
(rf/reg-sub :progress/get-props [:subs/get-derived-state] subs/get-progress-props)
(rf/reg-sub :date-field/get-props [:subs/get-derived-state] subs/get-date-field-props)
(rf/reg-sub :textarea-field/get-props [:subs/get-derived-state] subs/get-textarea-field-props)
(rf/reg-sub :textarea-field/get-many-field-props [:subs/get-derived-state] subs/get-textarea-field-many-props)
(rf/reg-sub :map/props subs/map-props)
(rf/reg-sub :subs/get-form-tick subs/get-form-tick)
(rf/reg-sub :help/get-menuitems subs/get-menuitems)
(rf/reg-sub :subs/platform-selected? subs/platform-selected?)